import {Activity, Task} from '../types/types'

export const manyEndActivities: Task[] = [
    {
        id: 'A',
        time: 2,
        startActivity: 1,
        endActivity: 2,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'B',
        time: 2,
        startActivity: 2,
        endActivity: 3,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'C',
        time: 2,
        startActivity: 3,
        endActivity: 4,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'D',
        time: 2,
        startActivity: 3,
        endActivity: 5,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
]

export const manyStartActivities: Task[] = [
    {
        id: 'A',
        time: 2,
        startActivity: 1,
        endActivity: 2,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'B',
        time: 2,
        startActivity: 2,
        endActivity: 3,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'C',
        time: 2,
        startActivity: 3,
        endActivity: 4,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'D',
        time: 2,
        startActivity: 5,
        endActivity: 2,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
]

export const correctDataset: Task[] = [
    {
        id: 'A',
        time: 2,
        startActivity: 1,
        endActivity: 2,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'B',
        time: 2,
        startActivity: 2,
        endActivity: 3,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'C',
        time: 2,
        startActivity: 3,
        endActivity: 4,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
    {
        id: 'D',
        time: 2,
        startActivity: 4,
        endActivity: 5,
        ES:0,
        EF:0,
        LS:0,
        LF:0,
        R: 0,
    },
]

export const testActivities: Activity[] = [
    {
        EF: 0,
        ES: 0,
        R: 0,
        connected: [],
        id: 1,
        isCritical: true,
        isEnd: false,
        isStart: true,
        nextTasks: [{
            EF: 2,
            ES: 0,
            LF: 2,
            LS:0,
            R: 0,
            endActivity: 2,
            id: 'A',
            startActivity: 1,
            time: 2
        }]
    },
    {
        EF: 2,
        ES: 2,
        R: 0,
        connected: [{
            EF: 2,
            ES: 0,
            LF: 2,
            LS:0,
            R: 0,
            endActivity: 2,
            id: 'A',
            startActivity: 1,
            time: 2
        }],
        id: 2,
        isCritical: true,
        isEnd: false,
        isStart: false,
        nextTasks: [{
            EF: 5,
            ES: 2,
            LF: 5,
            LS:2,
            R: 0,
            endActivity: 3,
            id: 'B',
            startActivity: 2,
            time: 3
        }]
    },
    {
        EF: 5,
        ES: 5,
        R: 0,
        connected: [{
            EF: 5,
            ES: 2,
            LF: 5,
            LS:2,
            R: 0,
            endActivity: 3,
            id: 'B',
            startActivity: 2,
            time: 3
        }],
        id: 3,
        isCritical: true,
        isEnd: false,
        isStart: false,
        nextTasks: [{
            EF: 9,
            ES: 5,
            LF: 9,
            LS:5,
            R: 0,
            endActivity: 4,
            id: 'C',
            startActivity: 3,
            time: 4
        }]
    },
    {
        EF: 9,
        ES: 9,
        R: 0,
        connected: [{
            EF: 9,
            ES: 5,
            LF: 9,
            LS:5,
            R: 0,
            endActivity: 4,
            id: 'C',
            startActivity: 3,
            time: 4
        }],
        id: 4,
        isCritical: true,
        isEnd: true,
        isStart: false,
        nextTasks: []
    }
]